name: Daily Python Run and Push

on:
  schedule:
    - cron: '0 23 * * *'    # 每天 23:00 UTC 執行（台灣時間早上 7:00）
  workflow_dispatch:        # 允許手動觸發

jobs:
  run-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  # 啟用 pip 快取

      - name: Cache system packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-packages-${{ hashFiles('.github/workflows/main.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-packages-

      - name: Install system dependencies and Chinese fonts
        run: |
          # 只有在快取未命中時才更新套件列表
          if [ ! -f /var/cache/apt/pkgcache.bin ] || [ $(find /var/cache/apt/pkgcache.bin -mtime +1) ]; then
            sudo apt-get update
          fi
          
          # 檢查字體是否已安裝，避免重複安裝
          if ! fc-list | grep -q "Noto Sans CJK"; then
            sudo apt-get install -y fontconfig
            sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
            sudo apt-get install -y fonts-wqy-microhei fonts-wqy-zenhei
            sudo fc-cache -fv
            echo "✅ 中文字體安裝完成"
          else
            echo "✅ 中文字體已存在，跳過安裝"
          fi
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MPLBACKEND: Agg  # 設置 matplotlib 使用非互動後端
        run: python main.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Daily update from GitHub Actions"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
